// Getters
export const GET_NAME = 'shared/GET_NAME';
export const GET_EMAIL = 'shared/GET_EMAIL';
export const GET_PASSWORD = 'shared/GET_PASSWORD';
export const GET_CONFIRM_PASSWORD = 'shared/GET_CONFIRM_PASSWORD';
export const GET_ALL_QUESTIONNAIRE = 'shared/GET_ALL_QUESTIONNAIRE';
export const GET_ALL_QUESTIONS = 'shared/GET_ALL_QUESTIONS';
export const GET_COUNTER_QUESTIONS = 'shared/GET_COUNTER_QUESTIONS';
export const GET_CURRENT_QUESTION = 'shared/GET_CURRENT_QUESTION';
export const GET_NEW_PASSWORD = 'shared/GET_NEW_PASSWORD';
export const GET_NEW_PASSWORD_CONFIRM = 'shared/GET_NEW_PASSWORD_CONFIRM';



// Mutations
export const MUTATE_UPDATE_NAME = 'shared/MUTATE_UPDATE_NAME';
export const MUTATE_UPDATE_EMAIL = 'shared/MUTATE_UPDATE_EMAIL';
export const MUTATE_UPDATE_PASSWORD = 'shared/MUTATE_UPDATE_PASSWORD';
export const MUTATE_UPDATE_CONFIRM_PASSWORD = 'shared/MUTATE_UPDATE_CONFIRM_PASSWORD';
export const MUTATE_UPDATE_ALL_QUESTIONNAIRE = 'shared/MUTATE_UPDATE_ALL_QUESTIONNAIRE';
export const MUTATE_UPDATE_ALL_QUESTIONS = 'shared/MUTATE_UPDATE_ALL_QUESTIONS';
export const MUTATE_UPDATE_COUNTER_QUESTIONS = 'shared/MUTATE_UPDATE_COUNTER_QUESTIONS';
export const MUTATE_UPDATE_CURRENT_QUESTION = 'shared/MUTATE_UPDATE_CURRENT_QUESTION';
export const MUTATE_UPDATE_NEW_PASSWORD = 'shared/MUTATE_UPDATE_NEW_PASSWORD';
export const MUTATE_UPDATE_NEW_PASSWORD_CONFIRM = 'shared/MUTATE_UPDATE_NEW_PASSWORD_CONFIRM';


// Actions
export const UPDATE_NAME = 'shared/UPDATE_NAME';
export const UPDATE_EMAIL = 'shared/UPDATE_EMAIL';
export const UPDATE_PASSWORD = 'shared/UPDATE_PASSWORD';
export const UPDATE_CONFIRM_PASSWORD = 'shared/UPDATE_CONFIRM_PASSWORD';
export const UPDATE_ALL_QUESTIONNAIRE = 'shared/UPDATE_ALL_QUESTIONNAIRE';
export const UPDATE_ALL_QUESTIONS = 'shared/UPDATE_ALL_QUESTIONS';
export const UPDATE_COUNTER_QUESTIONS = 'shared/UPDATE_COUNTER_QUESTIONS';
export const UPDATE_CURRENT_QUESTION = 'shared/UPDATE_CURRENT_QUESTION';
export const UPDATE_NEW_PASSWORD = 'shared/UPDATE_NEW_PASSWORD';
export const UPDATE_NEW_PASSWORD_CONFIRM = 'shared/UPDATE_NEW_PASSWORD_CONFIRM';
